import { createHash } from 'node:crypto';
import { shellQuote } from '../backends/kali.js';
import { initialHttpExchange, parseHttpCommand, parseStrictJson, HTTP_RESPONSE_LIMIT, type HttpObservation } from './http.js';

const hash = (bytes: Uint8Array) => createHash('sha256').update(bytes).digest('hex');
const FRAME = 'XLOOM_HTTP_V1\n';
export const REMOTE_HTTP_OUTPUT_LIMIT = Math.ceil(HTTP_RESPONSE_LIMIT * 4 / 3) + 8192;

// Fixed application code, never generated by a model. Runs in one SSH exec;
// Python's HTTP client does not follow redirects or execute response content.
const PROGRAM = String.raw`
import base64, datetime, http.client, json, signal, sys, urllib.parse
p=json.loads(base64.b64decode(sys.argv[1]).decode('utf-8'))
u=urllib.parse.urlsplit(p['url'])
body=base64.b64decode(p['body'])
headers=p['headers']
headers['host']=u.netloc
headers['content-length']=str(len(body))
headers['connection']='close'
now=lambda:datetime.datetime.now(datetime.timezone.utc).isoformat().replace('+00:00','Z')
result={'version':1,'url':p['url'],'method':p['method'],'requestSha256':__import__('hashlib').sha256(body).hexdigest(),'startedAt':now(),'status':None,'complete':False,'outcome':'not_started','response':''}
chunks=[]
connection=None
def timeout(signum, frame): raise TimeoutError('deadline')
signal.signal(signal.SIGALRM,timeout)
signal.setitimer(signal.ITIMER_REAL,p['timeoutMs']/1000)
try:
    cls=http.client.HTTPSConnection if u.scheme=='https' else http.client.HTTPConnection
    connection=cls(u.hostname,u.port,timeout=p['timeoutMs']/1000)
    result['outcome']='unknown'
    connection.request(p['method'],u.path+('?' + u.query if u.query else ''),body=body,headers=headers)
    response=connection.getresponse()
    result['status']=response.status
    if sum(len(k)+len(v)+4 for k,v in response.getheaders())>32768: raise ValueError('response header limit')
    remaining=p['limit']
    while True:
        data=response.read1(min(65536,remaining+1))
        if not data:
            if response.length not in (None,0): raise EOFError('incomplete response')
            result['complete']=True
            result['outcome']='completed'
            break
        if len(data)>remaining:
            chunks.append(data[:remaining])
            raise ValueError('response limit')
        chunks.append(data)
        remaining-=len(data)
except Exception as error:
    result['error']=type(error).__name__
finally:
    signal.setitimer(signal.ITIMER_REAL,0)
    if connection is not None: connection.close()
    result['endedAt']=now()
    result['response']=base64.b64encode(b''.join(chunks)).decode('ascii')
    print('XLOOM_HTTP_V1')
    print(json.dumps(result,separators=(',',':')),flush=True)
`;

export function remoteHttpRequest(command: string) {
  const input = parseHttpCommand(command), initial = initialHttpExchange(input, 'ssh');
  const payload = Buffer.from(JSON.stringify({ url: input.url.href, method: input.method, headers: input.headers,
    body: input.body.toString('base64'), timeoutMs: input.timeoutMs, limit: HTTP_RESPONSE_LIMIT })).toString('base64');
  if (payload.length > 65536) throw new Error('远端原生 HTTP 参数编码后不得超过 64 KiB；未启动 SSH');
  // Base64 is argv data and both arguments are shell-quoted. No user shell text
  // participates in the generated command. No remote file/install is needed.
  const generatedCommand = `python3 -I -c ${shellQuote(PROGRAM)} ${shellQuote(payload)}`;
  const incomplete = (): HttpObservation => ({ exchange: { ...initial, endedAt: new Date().toISOString(), outcome: 'unknown' },
    requestBody: input.body, responseBody: Buffer.alloc(0), text: '远端 HTTP 未取得完整记录；未重试，结果未知' });
  const decode = (stdout: Buffer): HttpObservation => {
    if (stdout.length > REMOTE_HTTP_OUTPUT_LIMIT || !stdout.subarray(0, FRAME.length).equals(Buffer.from(FRAME))) throw new Error('原生远端 HTTP 记录不完整或超限');
    const raw = parseStrictJson(stdout.subarray(FRAME.length)) as Record<string, unknown>;
    if (!raw || raw.version !== 1 || raw.url !== input.url.href || raw.method !== input.method || raw.requestSha256 !== initial.requestBodySha256 ||
      typeof raw.startedAt !== 'string' || typeof raw.endedAt !== 'string' || !Number.isFinite(Date.parse(raw.startedAt)) || !Number.isFinite(Date.parse(raw.endedAt)) ||
      Date.parse(raw.endedAt) < Date.parse(raw.startedAt) || !(raw.status === null || (Number.isInteger(raw.status) && Number(raw.status) >= 100 && Number(raw.status) <= 599)) ||
      typeof raw.complete !== 'boolean' || !['not_started', 'unknown', 'completed'].includes(String(raw.outcome)) ||
      typeof raw.response !== 'string' || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(raw.response)) throw new Error('原生远端 HTTP 记录与实际请求不匹配');
    const responseBody = Buffer.from(raw.response, 'base64');
    if (responseBody.length > HTTP_RESPONSE_LIMIT || (raw.complete && (raw.outcome !== 'completed' || raw.status === null || raw.error !== undefined)) || (!raw.complete && raw.outcome === 'completed')) throw new Error('原生远端 HTTP 完整性字段矛盾');
    const exchange = { ...initial, status: raw.status as number | null, startedAt: raw.startedAt, endedAt: raw.endedAt,
      complete: raw.complete, outcome: raw.outcome as typeof initial.outcome, responseBodySha256: hash(responseBody) };
    return { exchange, requestBody: input.body, responseBody,
      text: JSON.stringify({ exchange, responseBody: responseBody.toString('utf8'), ...(raw.error ? { error: String(raw.error) } : {}) }) };
  };
  return { command: generatedCommand, input, decode, incomplete };
}
